theme: minima
title: My Dive Into The IT Industry : Destined Outcome : Security Analyst (Yr 1) - Pen Tester (Yr 2) - CISO 
author: <3 ~ Charli ~ <3 
email: Char.tech22@outlook.com your-email@domain.com
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this
 # line in _config.yml. It will appear in your document head meta (for
 #Google search results) and in your feed.xml site description.

"I’m interested in learning how to code to contribute to the medical industry...I'm also interested in cyber security (pen testing)
  I’m currently learning Java, HTML, Splunk, Network Security & more ...Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: chardevie # DO NOT include the @ character, or else the build will fail!
github_username:  charli-rose # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
